collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
typography_spectrum: 0.4765958
color:
  saturation: 0.7978724
  brandStrength: 0.8361702
  lightness: 0.2851064
  brandColors:
    - '#0062A6'
    - '#0D0C0A'
    - '#FFFFFF'
    - '#4B4A4A'
    - '#7C7B79'
  rhythmicContrast: 0.5404255
layout_spectrum: 0.912766
name: 'Crowe Consulting '
