color:
  saturation: 0.7148936
  brandStrength: 0.8361702
  rhythmicContrast: 0.5381083
  brandColors:
    - '#0062A6'
    - '#0D0C0A'
    - '#FFFFFF'
    - '#4B4A4A'
    - '#7C7B79'
  lightness: 0.02296027
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
layout_spectrum: 0.912766
typography_spectrum: 0.6191489
name: 'Crowe Consulting '
